import type { AppData, Contact, Fund, Startup, Pair, StatusDef, CommEvent } from './types';

const c = (name: string, email: string): Contact => ({ name, email });

const funds: Fund[] = [
  {
    id: 'fund-01',
    fundName: 'Northstar Capital',
    city: 'Mumbai',
    focusAreas: ['Fintech', 'SaaS & Enterprise'],
    minTicket: 1,
    maxTicket: 5,
    stages: ['Seed', 'Series A'],
    locations: ['India'],
    priority: 'High',
    investorType: 'VC',
    contacts: [
      c('Aditya Rao', 'aditya.rao@northstarcap.com'),
      c('Meera Iyer', 'meera.iyer@northstarcap.com'),
      c('Karan Mehta', 'karan.mehta@northstarcap.com'),
      c('Sanya Kapoor', 'sanya.kapoor@northstarcap.com'),
      c('Rohan Verma', 'rohan.verma@northstarcap.com'),
      c('Divya Nair', 'divya.nair@northstarcap.com'),
      c('Arjun Malhotra', 'arjun.malhotra@northstarcap.com'),
      c('Priya Desai', 'priya.desai@northstarcap.com'),
      c('Vikram Shah', 'vikram.shah@northstarcap.com'),
      c('Neha Joshi', 'neha.joshi@northstarcap.com'),
    ],
  },
  {
    id: 'fund-02',
    fundName: 'Helix Ventures',
    city: 'San Francisco',
    focusAreas: ['AI & Deep Tech', 'SaaS & Enterprise'],
    minTicket: 10,
    maxTicket: null,
    stages: ['Series A', 'Series B'],
    locations: ['US', 'Global'],
    priority: 'High',
    investorType: 'VC',
    contacts: [
      c('Daniel Cho', 'daniel.cho@helixvc.com'),
      c('Sarah Lin', 'sarah.lin@helixvc.com'),
      c('Marcus Webb', 'marcus.webb@helixvc.com'),
      c('Olivia Brandt', 'olivia.brandt@helixvc.com'),
      c('Ethan Brooks', 'ethan.brooks@helixvc.com'),
      c('Grace Kim', 'grace.kim@helixvc.com'),
      c('Liam Foster', 'liam.foster@helixvc.com'),
      c('Ava Sullivan', 'ava.sullivan@helixvc.com'),
      c('Noah Bennett', 'noah.bennett@helixvc.com'),
    ],
  },
  {
    id: 'fund-03',
    fundName: 'Bloom & Co Angels',
    city: 'Bangalore',
    focusAreas: ['Apparel & Lifestyle', 'Consumer & D2C'],
    minTicket: null,
    maxTicket: 1,
    stages: ['Pre-seed', 'Seed'],
    locations: ['India'],
    priority: 'Medium',
    investorType: 'Angel',
    contacts: [
      c('Ritu Bhatia', 'ritu.bhatia@bloomangels.in'),
      c('Sameer Khanna', 'sameer.khanna@bloomangels.in'),
    ],
  },
  {
    id: 'fund-04',
    fundName: 'Terra Climate Partners',
    city: 'Berlin',
    focusAreas: ['Climate & Energy', 'Mobility & Logistics'],
    minTicket: 5,
    maxTicket: 15,
    stages: ['Series B', 'Series C+'],
    locations: ['Europe'],
    priority: 'High',
    investorType: 'VC',
    contacts: [
      c('Lukas Becker', 'lukas.becker@terraclimate.de'),
      c('Anna Schmidt', 'anna.schmidt@terraclimate.de'),
      c('Felix Wagner', 'felix.wagner@terraclimate.de'),
      c('Clara Hoffmann', 'clara.hoffmann@terraclimate.de'),
      c('Jonas Richter', 'jonas.richter@terraclimate.de'),
      c('Mia Krueger', 'mia.krueger@terraclimate.de'),
      c('Paul Zimmer', 'paul.zimmer@terraclimate.de'),
      c('Lena Vogel', 'lena.vogel@terraclimate.de'),
    ],
  },
  {
    id: 'fund-05',
    fundName: 'Skilling Frontier Fund',
    city: 'Singapore',
    focusAreas: ['EdTech & HR/Skilling', 'Media/Gaming/Creator'],
    minTicket: null,
    maxTicket: 2,
    stages: ['Seed', 'Series A'],
    locations: ['SEA'],
    priority: 'Medium',
    investorType: 'VC',
    contacts: [c('Wei Tan', 'wei.tan@skillingfrontier.sg')],
  },
  {
    id: 'fund-06',
    fundName: 'Omni Sector Holdings',
    city: 'London',
    focusAreas: ['Sector Agnostic'],
    minTicket: null,
    maxTicket: null,
    stages: [],
    locations: ['Global'],
    priority: 'Low',
    investorType: 'Family Office',
    contacts: [
      c('Charles Whitfield', 'charles.whitfield@omnisector.co.uk'),
      c('Eleanor Pryce', 'eleanor.pryce@omnisector.co.uk'),
      c('James Holloway', 'james.holloway@omnisector.co.uk'),
      c('Sophie Carrington', 'sophie.carrington@omnisector.co.uk'),
    ],
  },
  {
    id: 'fund-07',
    fundName: 'Crosswind Capital',
    city: 'Delhi',
    focusAreas: ['Fintech', 'Web3 & Crypto'],
    minTicket: 0.5,
    maxTicket: 3,
    stages: ['Pre-seed', 'Seed'],
    locations: ['India', 'Global'],
    priority: 'Medium',
    investorType: 'VC',
    contacts: [
      c('Rajesh Kumar', 'rajesh.kumar@crosswindcap.in'),
      c('Anjali Singh', 'anjali.singh@crosswindcap.in'),
      c('Vivek Chawla', 'vivek.chawla@crosswindcap.in'),
      c('Pooja Reddy', 'pooja.reddy@crosswindcap.in'),
      c('Nikhil Bansal', 'nikhil.bansal@crosswindcap.in'),
      c('Tara Sethi', 'tara.sethi@crosswindcap.in'), // index 5 ("Email 6") present, no higher indices
    ],
  },
  {
    id: 'fund-08',
    fundName: 'Pinnacle Family Office',
    city: 'Mumbai',
    focusAreas: ['Sector Agnostic', 'Health & Life Sciences'],
    minTicket: 2,
    maxTicket: null,
    stages: ['Series A', 'Series B', 'Series C+'],
    locations: [],
    priority: 'Low',
    investorType: 'Family Office',
    contacts: [
      c('Ananya Bose', 'ananya.bose@pinnaclefo.com'),
      c('Rahul Kapoor', 'rahul.kapoor@pinnaclefo.com'),
      { name: 'Priya Shah', email: null }, // known contact, email not yet captured
      c('Siddharth Rao', 'siddharth.rao@pinnaclefo.com'),
    ],
  },
  {
    id: 'fund-09',
    fundName: 'Lighthouse SaaS Fund',
    city: 'Pune',
    focusAreas: ['SaaS & Enterprise', 'AI & Deep Tech'],
    minTicket: 3,
    maxTicket: 12,
    stages: ['Seed', 'Series A'],
    locations: ['India', 'US'],
    priority: 'High',
    investorType: 'VC',
    contacts: [
      c('Amit Trivedi', 'amit.trivedi@lighthousesaas.com'),
      c('Kavya Menon', 'kavya.menon@lighthousesaas.com'),
      c('Rishi Pillai', 'rishi.pillai@lighthousesaas.com'),
      c('Shreya Gupta', 'shreya.gupta@lighthousesaas.com'),
      c('Aakash Jain', 'aakash.jain@lighthousesaas.com'),
      c('Ishita Mathur', 'ishita.mathur@lighthousesaas.com'),
      c('Varun Saxena', 'varun.saxena@lighthousesaas.com'),
      c('Nidhi Agarwal', 'nidhi.agarwal@lighthousesaas.com'),
    ],
  },
  {
    id: 'fund-10',
    fundName: 'Riverside Real Assets',
    city: 'Dubai',
    focusAreas: ['Real Estate & Construction', 'Travel & Hospitality'],
    minTicket: null,
    maxTicket: 6,
    stages: ['Series B', 'Series C+'],
    locations: ['Global'],
    priority: 'Low',
    investorType: null,
    contacts: [
      c('Omar Al-Farsi', 'omar.alfarsi@riversideassets.ae'),
      c('Layla Haddad', 'layla.haddad@riversideassets.ae'),
      c('Yusuf Nasser', 'yusuf.nasser@riversideassets.ae'),
    ],
  },
  {
    id: 'fund-11',
    fundName: 'FreshTable Ventures',
    city: 'Chicago',
    focusAreas: ['Food & FMCG', 'Consumer & D2C'],
    minTicket: 1,
    maxTicket: 4,
    stages: ['Seed', 'Series A'],
    locations: ['US', 'Europe'],
    priority: 'Medium',
    investorType: 'VC',
    contacts: [
      c('Megan Hayes', 'megan.hayes@freshtablevc.com'),
      c('Tyler Brooks', 'tyler.brooks@freshtablevc.com'),
      c('Chloe Adams', 'chloe.adams@freshtablevc.com'),
      c('Brandon Reyes', 'brandon.reyes@freshtablevc.com'),
      c('Hannah Price', 'hannah.price@freshtablevc.com'),
      c('Jordan Lee', 'jordan.lee@freshtablevc.com'),
      c('Natalie Cross', 'natalie.cross@freshtablevc.com'),
      c('Cameron Diaz', 'cameron.diaz2@freshtablevc.com'),
      c('Logan Pierce', 'logan.pierce@freshtablevc.com'),
    ],
  },
  {
    id: 'fund-12',
    fundName: 'Quantum Edge Capital',
    city: 'Tel Aviv',
    focusAreas: ['AI & Deep Tech', 'Web3 & Crypto'],
    minTicket: 6,
    maxTicket: 20,
    stages: ['Series A', 'Series B'],
    locations: ['Europe', 'Global'],
    priority: 'High',
    investorType: 'VC',
    contacts: [
      c('Itai Cohen', 'itai.cohen@quantumedge.il'),
      c('Noa Levi', 'noa.levi@quantumedge.il'),
      c('Eyal Mizrahi', 'eyal.mizrahi@quantumedge.il'),
      c('Maya Ben-David', 'maya.bendavid@quantumedge.il'),
      c('Tomer Avraham', 'tomer.avraham@quantumedge.il'),
      c('Shira Goldberg', 'shira.goldberg@quantumedge.il'),
      c('Omer Peretz', 'omer.peretz@quantumedge.il'),
    ],
  },
  {
    id: 'fund-13',
    fundName: 'Coral Reef Capital',
    city: 'Jakarta',
    focusAreas: ['Mobility & Logistics', 'Sector Agnostic'],
    minTicket: null,
    maxTicket: 10,
    stages: ['Pre-seed', 'Seed', 'Series A'],
    locations: ['SEA', 'India'],
    priority: 'Medium',
    investorType: 'Angel',
    contacts: [
      c('Budi Santoso', 'budi.santoso@coralreefcap.id'),
      c('Siti Rahma', 'siti.rahma@coralreefcap.id'),
      c('Andi Wijaya', 'andi.wijaya@coralreefcap.id'),
      c('Dewi Lestari', 'dewi.lestari@coralreefcap.id'),
      c('Eko Prasetyo', 'eko.prasetyo@coralreefcap.id'),
      c('Rina Hartono', 'rina.hartono@coralreefcap.id'),
      c('Agus Setiawan', 'agus.setiawan@coralreefcap.id'),
      c('Maya Putri', 'maya.putri@coralreefcap.id'),
      c('Hendra Gunawan', 'hendra.gunawan@coralreefcap.id'),
      c('Lina Wibowo', 'lina.wibowo@coralreefcap.id'),
    ],
  },
  {
    id: 'fund-14',
    fundName: 'Vantage Holdings',
    city: 'Toronto',
    focusAreas: ['Media/Gaming/Creator', 'Consumer & D2C'],
    minTicket: null,
    maxTicket: null,
    stages: ['Series C+'],
    locations: ['US', 'Europe', 'Global'],
    priority: null,
    investorType: 'Corporate',
    contacts: [
      c('Connor Murphy', 'connor.murphy@vantageholdings.ca'),
      c('Brianna Scott', 'brianna.scott@vantageholdings.ca'),
      c('Tyler Nguyen', 'tyler.nguyen@vantageholdings.ca'),
      c('Madison Clarke', 'madison.clarke@vantageholdings.ca'),
      c('Jacob Turner', 'jacob.turner@vantageholdings.ca'),
    ],
  },
];

const startups: Startup[] = [
  {
    id: 'startup-01',
    name: 'TallyForge',
    sector: 'Fintech',
    stage: 'Seed',
    raise: 2.5,
    location: 'India',
  },
  {
    id: 'startup-02',
    name: 'NimbusAI',
    sector: 'AI & Deep Tech',
    stage: 'Series A',
    raise: 20,
    location: 'US',
  },
  {
    id: 'startup-03',
    name: 'KadamWear',
    sector: 'Apparel & Lifestyle',
    stage: 'Pre-seed',
    raise: 0.5,
    location: 'India',
  },
  {
    id: 'startup-04',
    name: 'GreenVolt',
    sector: 'Climate & Energy',
    stage: 'Series B',
    raise: 8,
    location: 'Europe',
  },
  {
    id: 'startup-05',
    name: 'SkillBridge',
    sector: 'EdTech & HR/Skilling',
    stage: 'Seed',
    raise: 1.2,
    location: 'SEA',
  },
];

const statuses: StatusDef[] = [
  { id: 'status-01', label: 'Reached out – currently evaluating', order: 1, closed: false, color: 'slate' },
  { id: 'status-02', label: 'Interested to meet', order: 2, closed: false, color: 'blue' },
  { id: 'status-03', label: 'Meeting done', order: 3, closed: false, color: 'indigo' },
  { id: 'status-04', label: 'Interested for 2nd call', order: 4, closed: false, color: 'violet' },
  { id: 'status-05', label: 'Due Diligence', order: 5, closed: false, color: 'amber' },
  { id: 'status-06', label: 'Investment', order: 6, closed: true, color: 'emerald' },
  { id: 'status-07', label: 'Pass', order: 7, closed: true, color: 'rose' },
  { id: 'status-08', label: 'Pass after meeting done', order: 8, closed: true, color: 'rose' },
  { id: 'status-09', label: 'Pass after 2nd meeting', order: 9, closed: true, color: 'rose' },
  { id: 'status-10', label: 'Not a pass – re-evaluate later', order: 10, closed: false, color: 'amber' },
];

const pairs: Pair[] = [
  {
    id: 'pair-01',
    startupId: 'startup-01',
    fundId: 'fund-01',
    status: 'status-02', // Interested to meet
    description: 'Intro call scheduled after a warm referral from a portfolio founder.',
    mailLink: 'https://mail.google.com/mail/u/0/#inbox/placeholder-pair-01',
    followUpDate: '2026-07-02',
    matchedAt: '2026-06-10T09:15:00.000Z',
  },
  {
    id: 'pair-02',
    startupId: 'startup-01',
    fundId: 'fund-07',
    status: 'status-07', // Pass
    description: 'Fund passed, citing stage mismatch with their current fund cycle.',
    mailLink: 'https://mail.google.com/mail/u/0/#inbox/placeholder-pair-02',
    followUpDate: null,
    matchedAt: '2026-06-12T11:30:00.000Z',
  },
  {
    id: 'pair-03',
    startupId: 'startup-01',
    fundId: 'fund-13',
    status: 'status-03', // Meeting done
    description: 'First meeting completed; fund requested an updated financial model.',
    mailLink: 'https://mail.google.com/mail/u/0/#inbox/placeholder-pair-03',
    followUpDate: '2026-07-15',
    matchedAt: '2026-06-14T14:00:00.000Z',
  },
];

const events: CommEvent[] = [
  // pair-01 — Interested to meet
  {
    id: 'event-01',
    pairId: 'pair-01',
    date: '2026-06-10T10:00:00.000Z',
    type: 'outreach_sent',
    subject: 'Introduction: TallyForge x Northstar Capital',
    body: 'Sent a warm intro email with the deck attached.',
  },
  {
    id: 'event-02',
    pairId: 'pair-01',
    date: '2026-06-11T09:30:00.000Z',
    type: 'reply_received',
    subject: 'Re: Introduction: TallyForge x Northstar Capital',
    body: "Thanks for reaching out — would love to learn more, can we set up a call next week?",
  },
  // pair-02 — Pass
  {
    id: 'event-03',
    pairId: 'pair-02',
    date: '2026-06-12T12:00:00.000Z',
    type: 'outreach_sent',
    subject: 'Introduction: TallyForge x Crosswind Capital',
    body: 'Sent intro email with the deck attached.',
  },
  {
    id: 'event-04',
    pairId: 'pair-02',
    date: '2026-06-13T08:00:00.000Z',
    type: 'reply_received',
    subject: 'Re: Introduction: TallyForge x Crosswind Capital',
    body: 'Appreciate you thinking of us, but this is outside our current stage focus. Wishing you the best.',
  },
  // pair-03 — Meeting done
  {
    id: 'event-05',
    pairId: 'pair-03',
    date: '2026-06-14T14:30:00.000Z',
    type: 'outreach_sent',
    subject: 'Introduction: TallyForge x Coral Reef Capital',
    body: 'Sent intro email with the deck attached.',
  },
  {
    id: 'event-06',
    pairId: 'pair-03',
    date: '2026-06-15T10:00:00.000Z',
    type: 'reply_received',
    subject: 'Re: Introduction: TallyForge x Coral Reef Capital',
    body: "Interesting — let's set up time to chat.",
  },
  {
    id: 'event-07',
    pairId: 'pair-03',
    date: '2026-06-16T09:00:00.000Z',
    type: 'meeting_scheduled',
    subject: 'Call scheduled for Jun 18',
  },
  {
    id: 'event-08',
    pairId: 'pair-03',
    date: '2026-06-18T15:00:00.000Z',
    type: 'meeting_completed',
    subject: 'First call completed',
    body: 'Good first conversation; they requested an updated financial model.',
  },
];

export const seed: AppData = { funds, startups, pairs, statuses, events };
